AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Glue stuff to process CloudTrail logs consolidated by AWS Control Tower into a queryable table
Transform: AWS::Serverless-2016-10-31
Parameters:
  S3BucketName:
    Description: name of the S3 bucket that CT uses to consolidate cloudtrail logs
    Type: String
    AllowedPattern: aws\-controltower\-logs\-\d{12}.+
  S3LogsUrl:
    Description: log url to the cloudtrail logs, should look like this `s3://aws-controltower-logs-123443123456-us-east-1/o-s45wxfxxxx/AWSLogs/`
    Type: String
    AllowedPattern: s3:\/\/aws\-controltower\-logs\-\d{12}.+\/o-[a-z0-9]{10}\/AWSLogs\/
Resources:
  ParquetS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ct-parquet-${AWS::AccountId}-${AWS::Region}
#      BucketEncryption:
#        ServerSideEncryptionConfiguration:
#          - ServerSideEncryptionByDefault:
#              SSEAlgorithm: aws:kms
#              KMSMasterKeyID: KMS-KEY-ARN
# doesn't work cause guardrails :(
  AthenaResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub athena-query-results-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  AthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: cloudtrail-workgroup
      Description: for CloudTrail Reporting
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub s3://${AthenaResultsBucket}/
  CloudTrailDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: tables for auditing against consolidated CloudTrail
        Name: cloudtrail-db
  RawTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CloudTrailDatabase
      TableInput:
        Name: raw-cloudtrail-logs
        Description: JSON cloudtrail logs
        Parameters:
          classification: cloudtrail
          compressionType: gzip
          exclusions: !Sub '["${S3LogsUrl}**/Config/**","${S3LogsUrl}**/CloudTrail-Digest/**"]'
          jsonPath: $.Records[*]
        PartitionKeys:
        - Name: accountid
          Type: string
        - Name: logtype
          Type: string
        - Name: region
          Type: string
        - Name: year
          Type: string
        - Name: month
          Type: string
        - Name: day
          Type: string
        Retention: 0
        StorageDescriptor:
          Columns:
          - Name: eventversion
            Type: string
          - Name: useridentity
            Type: struct<type:string,principalId:string,arn:string,accountId:string,accessKeyId:string,sessionContext:struct<sessionIssuer:struct<type:string,principalId:string,arn:string,accountId:string,userName:string>,webIdFederationData:string,attributes:struct<mfaAuthenticated:string,creationDate:string>,ec2RoleDelivery:string>,invokedBy:string,userName:string,identityProvider:string>
          - Name: eventtime
            Type: string
          - Name: eventsource
            Type: string
          - Name: eventname
            Type: string
          - Name: awsregion
            Type: string
          - Name: sourceipaddress
            Type: string
          - Name: useragent
            Type: string
          - Name: requestparameters
            Type: string
          - Name: responseelements
            Type: string
          - Name: requestid
            Type: string
          - Name: eventid
            Type: string
          - Name: eventtype
            Type: string
          - Name: recipientaccountid
            Type: string
          - Name: errorcode
            Type: string
          - Name: errormessage
            Type: string
          - Name: resources
            Type: array<struct<accountId:string,type:string,ARN:string>>
          - Name: sharedeventid
            Type: string
          - Name: apiversion
            Type: string
          - Name: readonly
            Type: boolean
          - Name: managementevent
            Type: boolean
          - Name: eventcategory
            Type: string
          - Name: additionaleventdata
            Type: string
          - Name: vpcendpointid
            Type: string
          - Name: serviceeventdetails
            Type: string
          Compressed: false
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Ref S3LogsUrl
          NumberOfBuckets: 0
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              paths: additionaleventdata,apiversion,awsregion,errorcode,errormessage,eventcategory,eventid,eventname,eventsource,eventtime,eventtype,eventversion,managementevent,readonly,recipientaccountid,requestid,requestparameters,resources,responseelements,serviceeventdetails,sharedeventid,sourceipaddress,useragent,useridentity,vpcendpointid
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          SortColumns: []
          StoredAsSubDirectories: false
        TableType: EXTERNAL_TABLE
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: glue.amazonaws.com
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: ReadS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3BucketName}/*"
                  - !Sub "arn:aws:s3:::sam-cli-bucket-${AWS::AccountId}-${AWS::Region}/*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "${ParquetS3Bucket.Arn}/*"
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Description: discovers partitions in cloudtrail raw data
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref CloudTrailDatabase
      Configuration: '{"Version":1.0,"Grouping":{"TableGroupingPolicy":"CombineCompatibleSchemas"}}'
      Targets:
        CatalogTargets:
        - DatabaseName: !Ref CloudTrailDatabase
          Tables:
          - !Ref RawTable
      TablePrefix: raw
      SchemaChangePolicy:
        DeleteBehavior: LOG
        UpdateBehavior: LOG
  GlueJsonToParquetJob:
    Type: AWS::Glue::Job
    Properties:
        Command:
          Name: glueetl
          PythonVersion: '3'
          ScriptLocation: ./gluescript.py
        DefaultArguments:
          "--job-bookmark-option": job-bookmark-enable
          "--destbucket": !Ref ParquetS3Bucket
          "--database": !Ref CloudTrailDatabase
          "--srctable": !Ref RawTable
        ExecutionProperty:
          MaxConcurrentRuns: 1
        GlueVersion: '2.0'
        MaxRetries: 0
        Name: cloudtrail-to-parquet
        NumberOfWorkers: 10
        Role: !Ref GlueCrawlerRole
        Timeout: 2880
        WorkerType: G.1X
  ParquetCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Description: discovers partitions in cloudtrail raw data
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref CloudTrailDatabase
      Targets:
        S3Targets:
          - Path: !Sub "s3://${ParquetS3Bucket}/cloudtrail/"
      TablePrefix: pqt
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: LOG
  Workflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Nightly run
      Name: nightly-workflow
  StartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
      - CrawlerName: !Ref GlueCrawler
      Description: Early Morning
      Name: nightly-run-new
      Schedule: cron(33 7 * * ? *)
      StartOnCreation: true
      Type: SCHEDULED
      WorkflowName: !Ref Workflow
  AfterCrawlTrigger1:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
      - JobName: !Ref GlueJsonToParquetJob
      Description: after finish
      Name: after-json-crawl
      StartOnCreation: true
      Predicate:
        Conditions:
        - CrawlState: SUCCEEDED
          CrawlerName: !Ref GlueCrawler
          LogicalOperator: EQUALS
        Logical: ANY
      Type: CONDITIONAL
      WorkflowName: !Ref Workflow
  AfterCrawlTrigger2:
    Type: AWS::Glue::Trigger
    Properties:
      StartOnCreation: true
      Actions:
      - CrawlerName: !Ref ParquetCrawler
      Name: after-pq-convert
      Predicate:
        Conditions:
        - JobName: !Ref GlueJsonToParquetJob
          LogicalOperator: EQUALS
          State: SUCCEEDED
        Logical: ANY
      Type: CONDITIONAL
      WorkflowName:  !Ref Workflow
  SNSReportDistributionTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrailReportDistribution
  LambdaReporterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReadParquet
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "${ParquetS3Bucket.Arn}/*"
                  - !Sub "arn:aws:s3:::athena-query-results-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::athena-query-results-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
                  - !GetAtt ParquetS3Bucket.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref SNSReportDistributionTopic
  LambdaReporter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: query.lambda_handler
      Description: runs reports
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: "pqtcloudtrail"
          WORKGROUP: !Ref AthenaWorkgroup
          OUTPUT_BUCKET: !Ref AthenaResultsBucket
          DATABASE: !Ref CloudTrailDatabase
      Role: !GetAtt LambdaReporterRole.Arn
      Timeout: 600
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.glue"
              detail-type:
                - "Glue Crawler State Change"
              detail:
                crawlerName:
                  - !Ref ParquetCrawler
                state:
                  - Succeeded
  LambdaSender:
    Type: AWS::Serverless::Function
    Properties:
      Handler: send.lambda_handler
      Description: sends reports via SNS
      Runtime: python3.8
      Environment:
        Variables:
          SNS_TOPIC: !Ref SNSReportDistributionTopic
      Role: !GetAtt LambdaReporterRole.Arn
      Timeout: 600
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref AthenaResultsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: ".csv"
